name: mobile_charity_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.6.0
  provider: ^6.0.5
  go_router: ^7.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.5
  intl: ^0.18.1
  collection: ^1.17.0
  golden_toolkit: ^0.15.0
  mockito: ^5.4.0
  network_image_mock: ^2.1.1
  logger: ^1.4.0
  flutter_markdown: ^0.6.15
  firebase_analytics: ^10.4.3
  firebase_crashlytics: ^3.3.3
  image_picker: ^0.8.9
  firebase_storage: ^11.2.3
  geolocator: ^9.0.2
  share_plus: ^7.0.2
  http: ^0.13.6
  path_provider: ^2.0.15
  map_launcher: ^2.5.0+1
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.2.19
  app_tracking_transparency: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.5
  json_serializable: ^6.6.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/rectangular.png
    - assets/images/full.png
    - assets/images/profile_default_photo.svg
    - assets/images/logo4x.png
    - assets/images/rectangular4x.png
    - assets/images/ios_logo.png
    - .env

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
