// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLn8nP-vpSEmRsO07N2CyG5FVMTs44Hsw',
    appId: '1:480244158445:web:e5e779c8d1fd38519361e4',
    messagingSenderId: '480244158445',
    projectId: 'sermanos-c7580',
    authDomain: 'sermanos-c7580.firebaseapp.com',
    storageBucket: 'sermanos-c7580.appspot.com',
    measurementId: 'G-ESBLFY7ZQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2wri2UB0pZYHtBbhixaU98ttf1Dupt9M',
    appId: '1:480244158445:android:6842eb903cc8c24e9361e4',
    messagingSenderId: '480244158445',
    projectId: 'sermanos-c7580',
    storageBucket: 'sermanos-c7580.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMVQqZOXLM0y_CUtX121sjU1rJZHbG1d8',
    appId: '1:480244158445:ios:94da69a2d587b79b9361e4',
    messagingSenderId: '480244158445',
    projectId: 'sermanos-c7580',
    storageBucket: 'sermanos-c7580.appspot.com',
    iosClientId: '480244158445-rg70k0re7s2u94cunu2oir7enmvik36c.apps.googleusercontent.com',
    iosBundleId: 'ar.edu.itba.mobile.mobileCharityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMVQqZOXLM0y_CUtX121sjU1rJZHbG1d8',
    appId: '1:480244158445:ios:94da69a2d587b79b9361e4',
    messagingSenderId: '480244158445',
    projectId: 'sermanos-c7580',
    storageBucket: 'sermanos-c7580.appspot.com',
    iosClientId: '480244158445-rg70k0re7s2u94cunu2oir7enmvik36c.apps.googleusercontent.com',
    iosBundleId: 'ar.edu.itba.mobile.mobileCharityApp',
  );
}
